// Datos de ejemplo para el sistema de gimnasio
// Nombres peruanos realistas como valores por defecto

import type {
  Socio,
  PlanMembresia,
  Producto,
  Entrenador,
  RegistroAcceso,
  Venta,
  Gasto,
  Equipo,
  Clase,
  DashboardKPIs,
} from './types'
import { addDays, subDays, subMonths } from 'date-fns'

// ==================== PLANES DE MEMBRESÍA ====================
export const planesMembresia: PlanMembresia[] = [
  {
    id: 'plan-1',
    tenantId: 'gym-001',
    nombre: 'Plan Básico',
    descripcion: 'Acceso al gimnasio en horario regular',
    duracionDias: 30,
    precio: 99,
    caracteristicas: [
      'Acceso de lunes a viernes',
      'Horario: 6am - 10pm',
      'Uso de máquinas y pesas',
      'Casillero incluido',
    ],
    incluyeClases: false,
    incluyeEntrenadorPersonal: false,
    maxVisitasDiarias: 1,
    activo: true,
    orden: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'plan-2',
    tenantId: 'gym-001',
    nombre: 'Plan Premium',
    descripcion: 'Acceso completo con clases grupales',
    duracionDias: 30,
    precio: 159,
    caracteristicas: [
      'Acceso los 7 días',
      'Horario extendido: 5am - 11pm',
      'Clases grupales ilimitadas',
      'Área de cardio premium',
      'Casillero incluido',
      'Toalla de cortesía',
    ],
    incluyeClases: true,
    incluyeEntrenadorPersonal: false,
    maxVisitasDiarias: 2,
    activo: true,
    orden: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'plan-3',
    tenantId: 'gym-001',
    nombre: 'Plan VIP',
    descripcion: 'Experiencia completa con entrenador personal',
    duracionDias: 30,
    precio: 299,
    caracteristicas: [
      'Acceso 24/7',
      'Clases grupales ilimitadas',
      '4 sesiones con entrenador personal',
      'Evaluación física mensual',
      'Plan de nutrición personalizado',
      'Casillero premium',
      'Estacionamiento gratuito',
    ],
    incluyeClases: true,
    incluyeEntrenadorPersonal: true,
    maxVisitasDiarias: 3,
    activo: true,
    orden: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'plan-4',
    tenantId: 'gym-001',
    nombre: 'Plan Trimestral',
    descripcion: '3 meses con acceso completo - Ahorra 15%',
    duracionDias: 90,
    precio: 399,
    caracteristicas: [
      'Acceso los 7 días',
      'Clases grupales ilimitadas',
      'Congelamiento de hasta 15 días',
      '15% de descuento vs mensual',
    ],
    incluyeClases: true,
    incluyeEntrenadorPersonal: false,
    maxVisitasDiarias: 2,
    activo: true,
    orden: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// ==================== SOCIOS ====================
export const socios: Socio[] = [
  {
    id: 'socio-1',
    tenantId: 'gym-001',
    codigo: 'SOC-001',
    nombre: 'Carlos',
    apellido: 'Mendoza Quispe',
    email: 'carlos.mendoza@email.com',
    telefono: '+51 999 888 777',
    fechaNacimiento: new Date('1990-05-15'),
    genero: 'masculino',
    direccion: 'Av. Javier Prado 1250, San Isidro',
    avatar: '',
    contactoEmergencia: {
      nombre: 'María Mendoza',
      telefono: '+51 998 765 432',
      relacion: 'Hermana',
    },
    objetivosFisicos: ['Ganar masa muscular', 'Mejorar resistencia'],
    restriccionesMedicas: 'Ninguna',
    qrCode: 'QR-SOC-001',
    estado: 'activo',
    fechaRegistro: subMonths(new Date(), 6),
    ultimaVisita: subDays(new Date(), 1),
    puntosLealtad: 450,
    createdAt: subMonths(new Date(), 6),
    updatedAt: new Date(),
  },
  {
    id: 'socio-2',
    tenantId: 'gym-001',
    codigo: 'SOC-002',
    nombre: 'Ana',
    apellido: 'García Rodríguez',
    email: 'ana.garcia@email.com',
    telefono: '+51 987 654 321',
    fechaNacimiento: new Date('1995-08-22'),
    genero: 'femenino',
    direccion: 'Calle Las Flores 456, Miraflores',
    avatar: '',
    contactoEmergencia: {
      nombre: 'Pedro García',
      telefono: '+51 976 543 210',
      relacion: 'Padre',
    },
    objetivosFisicos: ['Perder peso', 'Tonificar'],
    qrCode: 'QR-SOC-002',
    estado: 'activo',
    fechaRegistro: subMonths(new Date(), 3),
    ultimaVisita: new Date(),
    puntosLealtad: 280,
    createdAt: subMonths(new Date(), 3),
    updatedAt: new Date(),
  },
  {
    id: 'socio-3',
    tenantId: 'gym-001',
    codigo: 'SOC-003',
    nombre: 'Miguel',
    apellido: 'Torres Huamán',
    email: 'miguel.torres@email.com',
    telefono: '+51 912 345 678',
    fechaNacimiento: new Date('1988-12-10'),
    genero: 'masculino',
    direccion: 'Jr. Cusco 789, Lima Centro',
    avatar: '',
    contactoEmergencia: {
      nombre: 'Laura Torres',
      telefono: '+51 923 456 789',
      relacion: 'Esposa',
    },
    objetivosFisicos: ['Salud general', 'Mejorar flexibilidad'],
    restriccionesMedicas: 'Lesión en rodilla derecha - evitar impacto',
    qrCode: 'QR-SOC-003',
    estado: 'vencido',
    fechaRegistro: subMonths(new Date(), 8),
    ultimaVisita: subDays(new Date(), 15),
    puntosLealtad: 120,
    createdAt: subMonths(new Date(), 8),
    updatedAt: subDays(new Date(), 15),
  },
  {
    id: 'socio-4',
    tenantId: 'gym-001',
    codigo: 'SOC-004',
    nombre: 'Lucía',
    apellido: 'Fernández Castro',
    email: 'lucia.fernandez@email.com',
    telefono: '+51 934 567 890',
    fechaNacimiento: new Date('1992-03-28'),
    genero: 'femenino',
    direccion: 'Av. Arequipa 2150, Lince',
    avatar: '',
    contactoEmergencia: {
      nombre: 'Carmen Castro',
      telefono: '+51 945 678 901',
      relacion: 'Madre',
    },
    objetivosFisicos: ['Preparación deportiva'],
    qrCode: 'QR-SOC-004',
    estado: 'congelado',
    fechaRegistro: subMonths(new Date(), 5),
    ultimaVisita: subDays(new Date(), 30),
    puntosLealtad: 350,
    notas: 'Congelamiento por viaje de trabajo - regresa en 2 semanas',
    createdAt: subMonths(new Date(), 5),
    updatedAt: subDays(new Date(), 30),
  },
  {
    id: 'socio-5',
    tenantId: 'gym-001',
    codigo: 'SOC-005',
    nombre: 'Roberto',
    apellido: 'Vargas Espinoza',
    email: 'roberto.vargas@email.com',
    telefono: '+51 956 789 012',
    fechaNacimiento: new Date('1985-07-03'),
    genero: 'masculino',
    direccion: 'Calle Los Álamos 321, Surco',
    avatar: '',
    contactoEmergencia: {
      nombre: 'Sandra Vargas',
      telefono: '+51 967 890 123',
      relacion: 'Esposa',
    },
    objetivosFisicos: ['Ganar masa muscular', 'Mejorar resistencia'],
    qrCode: 'QR-SOC-005',
    estado: 'activo',
    fechaRegistro: subMonths(new Date(), 12),
    ultimaVisita: subDays(new Date(), 2),
    puntosLealtad: 890,
    createdAt: subMonths(new Date(), 12),
    updatedAt: new Date(),
  },
]

// ==================== PRODUCTOS ====================
export const productos: Producto[] = [
  {
    id: 'prod-1',
    tenantId: 'gym-001',
    sku: 'SUP-PRO-001',
    nombre: 'Proteína Whey Gold Standard',
    descripcion: 'Proteína de suero de leche de alta calidad - 2.27kg',
    categoria: 'suplementos',
    costo: 180,
    precio: 249,
    margen: 27.7,
    stock: 15,
    stockMinimo: 5,
    stockMaximo: 30,
    estadoStock: 'ok',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    tenantId: 'gym-001',
    sku: 'SUP-CRE-001',
    nombre: 'Creatina Monohidratada',
    descripcion: 'Creatina pura - 300g',
    categoria: 'suplementos',
    costo: 45,
    precio: 69,
    margen: 34.8,
    stock: 8,
    stockMinimo: 10,
    stockMaximo: 25,
    estadoStock: 'bajo',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    tenantId: 'gym-001',
    sku: 'BEB-ENE-001',
    nombre: 'Bebida Energizante Monster',
    descripcion: 'Lata 473ml',
    categoria: 'bebidas',
    costo: 5,
    precio: 8,
    margen: 37.5,
    stock: 45,
    stockMinimo: 20,
    stockMaximo: 100,
    estadoStock: 'ok',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    tenantId: 'gym-001',
    sku: 'BEB-PRO-001',
    nombre: 'Batido de Proteínas RTD',
    descripcion: 'Batido listo para tomar - 330ml',
    categoria: 'bebidas',
    costo: 8,
    precio: 15,
    margen: 46.7,
    stock: 3,
    stockMinimo: 15,
    stockMaximo: 40,
    estadoStock: 'critico',
    fechaVencimiento: addDays(new Date(), 20),
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-5',
    tenantId: 'gym-001',
    sku: 'SNA-BAR-001',
    nombre: 'Barra de Proteínas Quest',
    descripcion: 'Barra de 60g - varios sabores',
    categoria: 'snacks',
    costo: 6,
    precio: 12,
    margen: 50,
    stock: 28,
    stockMinimo: 15,
    stockMaximo: 50,
    estadoStock: 'ok',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-6',
    tenantId: 'gym-001',
    sku: 'ACC-GUA-001',
    nombre: 'Guantes de Entrenamiento',
    descripcion: 'Guantes de cuero sintético - Talla M',
    categoria: 'accesorios',
    costo: 25,
    precio: 45,
    margen: 44.4,
    stock: 12,
    stockMinimo: 5,
    stockMaximo: 20,
    estadoStock: 'ok',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-7',
    tenantId: 'gym-001',
    sku: 'ACC-SHA-001',
    nombre: 'Shaker Blender Bottle',
    descripcion: 'Botella mezcladora 700ml',
    categoria: 'accesorios',
    costo: 18,
    precio: 35,
    margen: 48.6,
    stock: 20,
    stockMinimo: 8,
    stockMaximo: 30,
    estadoStock: 'ok',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-8',
    tenantId: 'gym-001',
    sku: 'SUP-PRE-001',
    nombre: 'Pre-Entreno C4 Original',
    descripcion: 'Pre-workout 30 servicios',
    categoria: 'suplementos',
    costo: 95,
    precio: 139,
    margen: 31.7,
    stock: 0,
    stockMinimo: 5,
    stockMaximo: 15,
    estadoStock: 'agotado',
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// ==================== REGISTROS DE ACCESO ====================
export const registrosAcceso: RegistroAcceso[] = [
  {
    id: 'acc-1',
    socioId: 'socio-1',
    socio: socios[0],
    tenantId: 'gym-001',
    fechaHora: new Date(),
    tipo: 'entrada',
    estado: 'permitido',
    metodo: 'qr',
  },
  {
    id: 'acc-2',
    socioId: 'socio-2',
    socio: socios[1],
    tenantId: 'gym-001',
    fechaHora: subDays(new Date(), 0),
    tipo: 'entrada',
    estado: 'permitido',
    metodo: 'codigo',
  },
  {
    id: 'acc-3',
    socioId: 'socio-5',
    socio: socios[4],
    tenantId: 'gym-001',
    fechaHora: subDays(new Date(), 0),
    tipo: 'entrada',
    estado: 'permitido',
    metodo: 'qr',
  },
  {
    id: 'acc-4',
    socioId: 'socio-3',
    socio: socios[2],
    tenantId: 'gym-001',
    fechaHora: subDays(new Date(), 0),
    tipo: 'entrada',
    estado: 'denegado',
    metodo: 'qr',
    notas: 'Membresía vencida',
  },
]

// ==================== EQUIPOS ====================
export const equipos: Equipo[] = [
  {
    id: 'equipo-1',
    tenantId: 'gym-001',
    nombre: 'Caminadora Technogym Run',
    tipo: 'Cardio',
    marca: 'Technogym',
    modelo: 'Run Personal',
    numeroSerie: 'TG-2023-001',
    fechaCompra: subMonths(new Date(), 18),
    precioCompra: 8500,
    ubicacion: 'Zona Cardio',
    estado: 'operativo',
    ultimoMantenimiento: subMonths(new Date(), 2),
    proximoMantenimiento: addDays(new Date(), 30),
    createdAt: subMonths(new Date(), 18),
    updatedAt: new Date(),
  },
  {
    id: 'equipo-2',
    tenantId: 'gym-001',
    nombre: 'Press de Banca',
    tipo: 'Pesas Libres',
    marca: 'Hammer Strength',
    modelo: 'Olympic Bench',
    numeroSerie: 'HS-2022-045',
    fechaCompra: subMonths(new Date(), 24),
    precioCompra: 3200,
    ubicacion: 'Zona de Pesas',
    estado: 'operativo',
    ultimoMantenimiento: subMonths(new Date(), 1),
    proximoMantenimiento: addDays(new Date(), 60),
    createdAt: subMonths(new Date(), 24),
    updatedAt: new Date(),
  },
  {
    id: 'equipo-3',
    tenantId: 'gym-001',
    nombre: 'Bicicleta Spinning',
    tipo: 'Cardio',
    marca: 'Life Fitness',
    modelo: 'IC7',
    numeroSerie: 'LF-2023-089',
    fechaCompra: subMonths(new Date(), 12),
    precioCompra: 2800,
    ubicacion: 'Sala de Spinning',
    estado: 'en_mantenimiento',
    ultimoMantenimiento: new Date(),
    notas: 'Cambio de pedales programado',
    createdAt: subMonths(new Date(), 12),
    updatedAt: new Date(),
  },
]

// ==================== CLASES ====================
export const clases: Clase[] = [
  {
    id: 'clase-1',
    tenantId: 'gym-001',
    nombre: 'Spinning Intenso',
    descripcion: 'Clase de ciclismo indoor de alta intensidad',
    entrenadorId: 'ent-1',
    entrenador: {} as any,
    fechaHora: addDays(new Date(), 1),
    duracionMinutos: 45,
    capacidadMaxima: 20,
    inscritos: 15,
    ubicacion: 'Sala de Spinning',
    tipo: 'grupal',
    activa: true,
  },
  {
    id: 'clase-2',
    tenantId: 'gym-001',
    nombre: 'Yoga Flow',
    descripcion: 'Clase de yoga para todos los niveles',
    entrenadorId: 'ent-2',
    entrenador: {} as any,
    fechaHora: addDays(new Date(), 1),
    duracionMinutos: 60,
    capacidadMaxima: 15,
    inscritos: 12,
    ubicacion: 'Sala Multiusos',
    tipo: 'grupal',
    activa: true,
  },
  {
    id: 'clase-3',
    tenantId: 'gym-001',
    nombre: 'CrossFit WOD',
    descripcion: 'Entrenamiento funcional de alta intensidad',
    entrenadorId: 'ent-1',
    entrenador: {} as any,
    fechaHora: addDays(new Date(), 2),
    duracionMinutos: 50,
    capacidadMaxima: 12,
    inscritos: 12,
    ubicacion: 'Zona Funcional',
    tipo: 'grupal',
    activa: true,
  },
]

// ==================== KPIs DEL DASHBOARD ====================
export const dashboardKPIs: DashboardKPIs = {
  sociosActivos: 234,
  sociosTendencia: 12,
  ingresosHoy: 2450,
  ingresosTendencia: 8,
  renovacionesPendientes: 18,
  alertasStock: 3,
  asistenciaHoy: 67,
  asistenciaTendencia: 5,
}

// ==================== DATOS PARA GRÁFICOS ====================
export const ingresosUltimos30Dias = Array.from({ length: 30 }, (_, i) => ({
  fecha: subDays(new Date(), 29 - i).toISOString().split('T')[0],
  membresias: Math.floor(Math.random() * 2000) + 1500,
  nutricion: Math.floor(Math.random() * 800) + 200,
}))

export const asistenciaUltimas2Semanas = Array.from({ length: 14 }, (_, i) => ({
  fecha: subDays(new Date(), 13 - i).toISOString().split('T')[0],
  asistencia: Math.floor(Math.random() * 50) + 40,
}))

export const desglosIngresos = [
  { categoria: 'Membresías', valor: 45600, porcentaje: 68 },
  { categoria: 'Suplementos', valor: 12300, porcentaje: 18 },
  { categoria: 'Accesorios', valor: 5400, porcentaje: 8 },
  { categoria: 'Bebidas', valor: 2700, porcentaje: 4 },
  { categoria: 'Otros', valor: 1340, porcentaje: 2 },
]

export const productosTopVentas = [
  { nombre: 'Proteína Whey Gold', vendidos: 45, ingresos: 11205 },
  { nombre: 'Barra Quest', vendidos: 120, ingresos: 1440 },
  { nombre: 'Creatina Mono', vendidos: 28, ingresos: 1932 },
  { nombre: 'Shaker Bottle', vendidos: 35, ingresos: 1225 },
  { nombre: 'Monster Energy', vendidos: 89, ingresos: 712 },
]

export const sociosProximosVencer = socios.filter((s) => s.estado === 'activo').slice(0, 5)

// ==================== GASTOS DEL MES ====================
export const gastosDelMes: Gasto[] = [
  {
    id: 'gasto-1',
    tenantId: 'gym-001',
    categoria: 'alquiler',
    descripcion: 'Alquiler del local - Marzo 2024',
    monto: 8500,
    fecha: new Date(),
    usuarioId: 'user-1',
    createdAt: new Date(),
  },
  {
    id: 'gasto-2',
    tenantId: 'gym-001',
    categoria: 'sueldos',
    descripcion: 'Planilla de personal - Marzo 2024',
    monto: 15200,
    fecha: new Date(),
    usuarioId: 'user-1',
    createdAt: new Date(),
  },
  {
    id: 'gasto-3',
    tenantId: 'gym-001',
    categoria: 'servicios',
    descripcion: 'Luz, agua e internet',
    monto: 2800,
    fecha: new Date(),
    usuarioId: 'user-1',
    createdAt: new Date(),
  },
  {
    id: 'gasto-4',
    tenantId: 'gym-001',
    categoria: 'mantenimiento',
    descripcion: 'Reparación de caminadora',
    monto: 450,
    fecha: subDays(new Date(), 5),
    usuarioId: 'user-1',
    createdAt: subDays(new Date(), 5),
  },
]
